[package]
name = "compute-shader-hello"
version = "0.1.0"
authors = ["Raph Levien <raph@google.com>"]
license = "MIT/Apache-2.0"
edition = "2021"

[dependencies]
wgpu = "0.11.0"
env_logger = "0.8"
pollster = "0.2"
bytemuck = { version = "1.7", features = ["derive"] }
